# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'
 inhibit_all_warnings!

target 'TodayPoetry' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya/ReactiveSwift', '~> 13.0'
pod 'Moya/RxSwift', '~> 13.0'
pod 'Kingfisher', '~> 5.0'
pod 'SnapKit', '~> 5.0.0'
pod 'RealmSwift'
pod 'liquid-swipe'
pod 'FloatingPanel'


  target 'TodayPoetryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodayPoetryUITests' do
    # Pods for testing
  end

end
